/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform -t
Author: Jovian Blaze (https://sketchfab.com/Jovian_Blaze)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hallow-cube-b702b517a0d3499fb0cb9b92b7bb413d
Title: Hallow Cube
*/

import * as THREE from 'three';
import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei/native';
import {GLTF} from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Plane005_0: THREE.Mesh;
    Plane004_0: THREE.Mesh;
    Plane003_0: THREE.Mesh;
    Plane002_0: THREE.Mesh;
    Plane001_0: THREE.Mesh;
    Cube_0: THREE.Mesh;
    Plane_0: THREE.Mesh;
  };
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
  };
};

export default function Scene(props: JSX.IntrinsicElements['group']) {
  const {nodes, materials} = useGLTF('/scene-transformed.glb') as GLTFResult;
  // return null;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Plane005_0.geometry}
          material={materials['Material.001']}
          position={[-1, 0.01, -0.01]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.88}
        />
        <mesh
          geometry={nodes.Plane004_0.geometry}
          material={materials['Material.001']}
          position={[1.01, 0.01, -0.01]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.88}
        />
        <mesh
          geometry={nodes.Plane003_0.geometry}
          material={materials['Material.001']}
          position={[0, 0.01, -1.01]}
          scale={0.88}
        />
        <mesh
          geometry={nodes.Plane002_0.geometry}
          material={materials['Material.001']}
          position={[0, 1, 0.01]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.88}
        />
        <mesh
          geometry={nodes.Plane001_0.geometry}
          material={materials['Material.001']}
          position={[0, -0.01, 1]}
          rotation={[-Math.PI, 0, 0]}
          scale={0.88}
        />
        <mesh geometry={nodes.Cube_0.geometry} material={materials.Material} />
        <mesh
          geometry={nodes.Plane_0.geometry}
          material={materials['Material.001']}
          position={[0, -1, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.88}
        />
      </group>
    </group>
  );
}

// useGLTF.preload(require('./scene-transformed.glb'));
